Models/materiales.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Fallas_IMSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class materiales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public materiales()
        {
            this.existencias = new HashSet<existencias>();
        }
    
        public int Id_material { get; set; }
        public string nombre { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public int id_tipo_hardware { get; set; }
        public string centro_costos { get; set; }
        public string nombre_proyecto { get; set; }
        public int id_estado { get; set; }
        public string comentarios { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<existencias> existencias { get; set; }
        public virtual material_estados material_estados { get; set; }
        public virtual tipo_hardware tipo_hardware { get; set; }
    }
}

Controllers/MaterialesController.cs
using Sistema_Fallas_IMSS.Models;
using Sistema_Fallas_IMSS.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace Sistema_Fallas_IMSS.Controllers
{
    public class MaterialesController : Controller
    {
        // GET: Materiales
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MaterialesGrid()
        {
            using(var context = new IMSSEntities())
            {
                List<VM_MaterialesCatalogo> materiales = (from material in context.materiales
                                                    join tipo in context.tipo_hardware on material.id_tipo_hardware equals tipo.Id_tipo_hardware
                                                    join estados in context.material_estados on material.id_estado equals estados.Id_estado
                                                    select new VM_MaterialesCatalogo
                                                    {
                                                        Id_material = material.Id_material,
                                                        Nombre = material.nombre,
                                                        Marca = material.marca,
                                                        Modelo= material.modelo,
                                                        Tipo_hardware = tipo.tipo_producto,
                                                        Centro_costos = material.centro_costos,
                                                        Proyecto = material.nombre_proyecto,
                                                        Estado = estados.nombre,
                                                        Comentarios = material.comentarios,
                                                    }).ToList();

                return PartialView("_MaterialesGrid",materiales);
            }
        }

        public ActionResult ExistenciaGrid()
        {
            using(var context = new IMSSEntities())
            {
                List<VM_Existencias> existencias = (from existencia in context.existencias
                                                    join material in context.materiales
                                                    on existencia.id_material equals material.Id_material
                                                    join areas in context.areas_imss
                                                    on existencia.id_area equals areas.Id_area
                                                    select new VM_Existencias
                                                    {
                                                        Id_existencia = existencia.Id_existencia,
                                                        Material = material.nombre + " " + material.marca + " " + material.modelo,
                                                        Pc = existencia.pc,
                                                        Cuenta = existencia.cuenta,
                                                        Nombre_persona = existencia.nombre_persona,
                                                        Nsm = existencia.nsm,
                                                        Nnn = existencia.nnn,
                                                        Direccion_ip = existencia.direccion_ip,
                                                        Serial = existencia.serial,
                                                        Area = areas.nombre_area,
                                                        Tipo_existencia = existencia.tipo_existencia,
                                                    }).ToList();

                return PartialView("_ExistenciasGrid", existencias);
            }    
        }

        public ActionResult TiposHardwareGrid()
        {
            using(var context = new IMSSEntities())
            {
                List<VM_TipoHardware> tipos = (from tipo in context.tipo_hardware
                                               select new VM_TipoHardware
                                               {
                                                   Id_tipo_hardware = tipo.Id_tipo_hardware,
                                                   Tipo_producto = tipo.tipo_producto,
                                               }).ToList();

                return PartialView("_TiposHardwareGrid", tipos);
            }
        }

        [HttpPost]
        public ActionResult AbrirModalMaterial(int _id_material)
        {
            using (var context = new IMSSEntities())
            {
                VM_MaterialesCatalogo data = new VM_MaterialesCatalogo();
                data.Tipos = (from tipos in context.tipo_hardware
                              select new SelectListItem
                              {
                                  Value = tipos.Id_tipo_hardware.ToString(),
                                  Text = tipos.tipo_producto,
                              }).ToList();
                data.Estados = (from estados in context.material_estados
                                select new SelectListItem
                                {
                                    Value = estados.Id_estado.ToString(),
                                    Text = estados.nombre,
                                }).ToList();

                if (_id_material > 0)
                {
                    var material = context.materiales.Find(_id_material);

                    data.Id_material = material.Id_material;
                    data.Nombre = material.nombre;
                    data.Marca = material.marca;
                    data.Modelo = material.modelo;
                    data.Centro_costos = material.centro_costos;
                    data.Proyecto = material.nombre_proyecto;
                    data.Tipo_hardware = material.id_tipo_hardware.ToString();
                    data.Estado = material.id_estado.ToString();
                    data.Comentarios = material.comentarios;


                    return PartialView("_ModalMaterial", data);
                }
                data.Estado = "1";
                return PartialView("_ModalMaterial", data);
            }
        }

        [HttpPost]
        public ActionResult AbrirModalExistencias(int _id_existencia)
        {
            using (var context = new IMSSEntities())
            {
                VM_Existencias data = new VM_Existencias();

                if (_id_existencia > 0)
                {
                    data = (from existencia in context.existencias
                            join material in context.materiales
                            on existencia.id_material equals material.Id_material
                            join areas in context.areas_imss
                            on existencia.id_area equals areas.Id_area
                            where existencia.Id_existencia == _id_existencia
                            select new VM_Existencias
                            {
                                Id_existencia = existencia.Id_existencia,
                                Material = material.Id_material.ToString(),
                                Pc = existencia.pc,
                                Area = areas.Id_area.ToString(),
                                Cuenta = existencia.cuenta,
                                Nombre_persona = existencia.nombre_persona,
                                Nsm = existencia.nsm,
                                Nnn = existencia.nnn,
                                Direccion_ip = existencia.direccion_ip,
                                Serial = existencia.serial,
                                Tipo = existencia.tipo_existencia == 1,
                                Tipo_existencia = existencia.tipo_existencia,
                            }).FirstOrDefault();
                }



                data.Materiales = context.materiales.Select(model => new SelectListItem
                {
                    Value = model.Id_material.ToString(),
                    Text = model.nombre + " " + model.marca + " " + model.modelo,
                }).ToList();
                data.Areas = context.areas_imss.Select(model => new SelectListItem
                    {
                        Value = model.Id_area.ToString(),
                        Text = model.nombre_area,
                    }).ToList();
       
              return PartialView("_ModalExistencia", data);
            }
        }

        [HttpPost]
        public ActionResult AbrirModalTipo(int _id_tipo)
        {
            using(var context = new IMSSEntities())
            {
                VM_TipoHardware data = new VM_TipoHardware();
                if (_id_tipo > 0)
                {
                    var tipo = context.tipo_hardware.Find(_id_tipo);
                    data.Id_tipo_hardware = _id_tipo;
                    data.Tipo_producto = tipo.tipo_producto;

                    return PartialView("_ModalTipo", data);
                }
                return PartialView("_ModalTipo", data);
            }
        }
        [HttpPost]
        public int RegistrarEditarExistencia(VM_Existencias _existencia)
        {
            using (var context = new IMSSEntities())
            {
                using(var transaction = context.Database.BeginTransaction())
                {
                    try
                    {

                        if (_existencia.Id_existencia > 0)
                        {
                            var existencia = context.existencias.Find(_existencia.Id_existencia);
                            existencia.id_material = Convert.ToInt32(_existencia.Material);
                            existencia.pc = _existencia.Pc;
                            existencia.cuenta = _existencia.Cuenta;

Views/Materiales/Index.cshtml
@using NonFactors.Mvc.Grid
@model Sistema_Fallas_IMSS.ViewModels.VM_Materiales
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="materiales-tab" data-bs-toggle="tab" data-bs-target="#materiales" type="button" role="tab" aria-controls="materiales" aria-selected="true">Materiales</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="existencias-tab" data-bs-toggle="tab" data-bs-target="#existencias" type="button" role="tab" aria-controls="existencias" aria-selected="false">Existencias</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="tipos-tab" data-bs-toggle="tab" data-bs-target="#tipos" type="button" role="tab" aria-controls="tipos" aria-selected="false">Tipos Hardware</button>
    </li>
</ul>
<div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="materiales" role="tabpanel" aria-labelledby="materiales-tab">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <section class="content-header">
                    <div class="row bottom30">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <h3 style="margin-top: 10px; text-align:center;">Materiales</h3>
                        </div>
                    </div>
                </section>
                <section class="content">
                    <br />
                    <div>
                        <button class="btn btn-primary" onclick="AbrirModalMaterial(0)">Registrar Material</button>
                    </div>
                    <br />
                    @Html.AjaxGrid(Url.Action("MaterialesGrid", "Materiales"),
                        new { id = "gridMateriales", name = "gridMateriales" })
                </section>
            </div>
        </div>
    </div>

    <div class="tab-pane fade" id="existencias" role="tabpanel" aria-labelledby="existencias-tab">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <section class="content-header">
                    <div class="row bottom30">
                        <br />
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <h3 style="margin-top: 10px; text-align:center;">Existencias</h3>
                        </div>
                    </div>
                </section>
                <section class="content">
                    <br />
                    <div>
                        <button class="btn btn-primary" onclick="AbrirModalExistencia(0)">Registrar Existencia</button>
                    </div>
                    <br />
                    @Html.AjaxGrid(Url.Action("ExistenciaGrid", "Materiales"),
                        new { id = "gridExistencia", name = "gridExistencia" })
                </section>
            </div>
        </div>
    </div>
    <div class="tab-pane fade" id="tipos" role="tabpanel" aria-labelledby="tipos-tab">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <section class="content-header">
                    <div class="row bottom30">
                        <br />
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <h3 style="margin-top: 10px; text-align:center;">Tipos de Hardware</h3>
                        </div>
                    </div>
                </section>
                <section class="content">
                    <br />
                    <div>
                        <button class="btn btn-primary" onclick="AbrirModalTipo(0)">Agregar nuevo</button>
                    </div>
                    <br />
                    @Html.AjaxGrid(Url.Action("TiposHardwareGrid", "Materiales"),
                        new { id = "gridTipos", name = "gridTipos" })
                </section>
            </div>
        </div>
    </div>
    <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">

    </div>
</div>


<!--Modal para Editar/Crear Materiales-->
<div id="mdl_Materiales" class="modal fade" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Material</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <br />
            <div class="modal-body">

                <!-- PartialView _ModalMaterial.cshtml -->

            </div>
            <!-- Modal footer -->
            <div class=" modal-footer">
                <button type="button" class="btn btn-success" onclick="RegistrarEditarMaterial()">Guardar</button>
            </div>
        </div>
    </div>
</div>
<!--Modal para Editar/Crear Existencias-->
<div id="mdl_Existencia" class="modal fade" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Existencia</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <br />
            <div class="modal-body">

                <!-- PartialView _ModalExistencias.cshtml -->

            </div>
            <!-- Modal footer -->
            <div class=" modal-footer">
                <button type="button" class="btn btn-success" onclick="RegistrarEditarExistencia()">Guardar</button>
            </div>
        </div>
    </div>
</div>
<!--Modal para Editar/Crear Tipos-->
<div id="mdl_Tipo" class="modal fade" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Tipo de Hardware</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <br />
            <div class="modal-body">

                <!-- PartialView _ModalTipos.cshtml -->

            </div>
            <!-- Modal footer -->
            <div class=" modal-footer">
                <button type="button" class="btn btn-success" onclick="RegistrarEditarTipo()">Guardar</button>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/MvcGrid/mvc-grid.js"></script>
<script type="text/javascript">

    window.onload = (event) => {

        [].forEach.call(document.getElementsByClassName('mvc-grid'), function (element) {
            new MvcGrid(element);
        });
    }
    function AbrirModalMaterial(id_material) {
        $.ajax({
            type: "POST",
            url: '@Href("~/Materiales/AbrirModalMaterial")',
            data: JSON.stringify({ _id_material: id_material }),
            contentType: "application/json; charset=utf-8",
            dataType: "html",
            success: function (response) {

                $("#mdl_Materiales").find(".modal-body").html(response);
                $("#mdl_Materiales").modal('show');

            },
            failure: function (response) {
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            },
        });
    }

    function AbrirModalExistencia(id_existencia) {
         $.ajax({
            type: "POST",
            url: '@Href("~/Materiales/AbrirModalExistencias")',
             data: JSON.stringify({ _id_existencia: id_existencia }),
            contentType: "application/json; charset=utf-8",
            dataType: "html",
            success: function (response) {

                $("#mdl_Existencia").find(".modal-body").html(response);
                $("#mdl_Existencia").modal('show');

            },
            failure: function (response) {
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            },
        });
    }

    function AbrirModalTipo(id_tipo) {
         $.ajax({
            type: "POST",
            url: '@Href("~/Materiales/AbrirModalTipo")',
            data: JSON.stringify({ _id_tipo: id_tipo }),
            contentType: "application/json; charset=utf-8",
            dataType: "html",
            success: function (response) {

                $("#mdl_Tipo").find(".modal-body").html(response);
                $("#mdl_Tipo").modal('show');

            },
            failure: function (response) {
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            },
        });
    }

    function RegistrarEditarMaterial() {
        var formData = new FormData();
        formData.append("Id_material", $("#Id_material").val());
        formData.append("Nombre", $("#Nombre").val());
        formData.append("Marca", $("#Marca").val());
        formData.append("Modelo", $("#Modelo").val());
        formData.append("Centro_costos", $("#Centro_costos").val());
        formData.append("Proyecto", $("#Proyecto").val());
        formData.append("Tipo_hardware", $("#Tipo_hardware").val());
        formData.append("Estado", $("#Estado").val());
        formData.append("Comentarios", $("#Comentarios").val());

         $.ajax({
            type: "POST",
            url: '@Href("~/Materiales/RegistrarEditarMaterial")',
            data: formData,
            contentType: false,
            dataType: "json",
            cache: false,
            processData: false,
            success: function (response) {

                if (response == 1) {
                    $("#mdl_Materiales").modal('hide');
                    var grid = new MvcGrid(document.querySelector("#gridMateriales"))
                    grid.reload();
                }

            },
            failure: function (response) {
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            },
        });
    }

    function RegistrarEditarExistencia() {

        var check = document.getElementById('Tipo');

        var formData = new FormData();
        formData.append("Id_existencia", $("#Id_existencia").val());
        formData.append("Nombre_persona", $("#Nombre_persona").val());
        formData.append("Material", $("#Material").val());
        formData.append("Area", $("#Area").val());
        formData.append("Pc", $("#Pc").val());
        formData.append("Cuenta", $("#Cuenta").val());
        formData.append("Direccion_ip", $("#Direccion_ip").val());
        formData.append("Serial", $("#Serial").val());
        formData.append("Nsm", $("#Nsm").val());
        formData.append("Nnn", $("#Nnn").val());
        
        if (check.checked) {
            formData.append("Tipo_existencia", 1);
        } else {
            formData.append("Tipo_existencia", 0);
        }

         $.ajax({
            type: "POST",
            url: '@Href("~/Materiales/RegistrarEditarExistencia")',
            data: formData,
            contentType: false,
            dataType: "json",
            cache: false,
            processData: false,
            success: function (response) {

                if (response == 1) {
                    $("#mdl_Existencia").modal('hide');
                    var grid = new MvcGrid(document.querySelector("#gridExistencias"))
                    grid.reload();
                }

            },
            failure: function (response) {
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            },
        });
    }

    function RegistrarEditarTipo() {

        var formData = new FormData();
        formData.append("Id_tipo_hardware", $("#Id_tipo_hardware").val());
        formData.append("Tipo_producto", $("#Tipo_producto").val());

         $.ajax({
            type: "POST",
            url: '@Href("~/Materiales/RegistrarEditarTipo")',
            data: formData,
            contentType: false,
            dataType: "json",
            cache: false,
            processData: false,
            success: function (response) {

                if (response == 1) {
                    $("#mdl_Tipo").modal('hide');
                    var grid = new MvcGrid(document.querySelector("#gridTipos"))
                    grid.reload();
                }

            },
            failure: function (response) {
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            },
        });
    }

</script>

Views/Materiales/_ExistenciasGrid.cshtml
@using NonFactors.Mvc.Grid
@model List<Sistema_Fallas_IMSS.ViewModels.VM_Existencias>
@(Html.Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.Id_existencia).Hidden();
        columns.Add(model => model.Tipo_existencia).Titled("Tipo existencia").Encoded(false).RenderedAs(model => model.Tipo_existencia == 1 ? "Global" : "Personal");
        columns.Add(model => model.Material).Titled("Nombre");
        columns.Add(model => model.Nombre_persona).Titled("Persona");
        columns.Add(model => model.Direccion_ip).Titled("Direccion IP");
        columns.Add(model => model.Pc).Titled("Pc");
        columns.Add(model => model.Cuenta).Titled("Cuenta");
        columns.Add(model => model.Nsm).Titled("Nsm");
        columns.Add(model => model.Nnn).Titled("Nnn");
        columns.Add(model => model.Serial).Titled("Centro de costos");
        columns.Add(model => model.Id_existencia).Titled("Editar").Encoded(false).Css("text-center").RenderedAs(model => $"<a href='#' onclick='AbrirModalExistencia({model.Id_existencia})' data-placement='left'><span style='text-align:center'><i class='fa-solid fa-pen-to-square btn btn-info'></i></span></a>");
    })
.Empty("Sin registros encontrados")
.Named("gridExistencias")
.Id("gridExistencias")
.Pageable(pager =>
{
    pager.RowsPerPage = 10;
})
)

Views/Materiales/_MaterialesGrid.cshtml
@using NonFactors.Mvc.Grid
@model List<Sistema_Fallas_IMSS.ViewModels.VM_MaterialesCatalogo>
@(Html.Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.Id_material).Hidden();
        columns.Add(model => model.Nombre).Titled("Nombre");
        columns.Add(model => model.Marca).Titled("Marca");
        columns.Add(model => model.Modelo).Titled("Modelo");
        columns.Add(model => model.Tipo_hardware).Titled("Tipo de Hardware");
        columns.Add(model => model.Centro_costos).Titled("Centro de costos");
        columns.Add(model => model.Proyecto).Titled("Proyecto");
        columns.Add(model => model.Estado).Titled("Estado");
        columns.Add(model => model.Comentarios).Titled("Comentarios");
        columns.Add(model => model.Id_material).Titled("Editar").Encoded(false).Css("text-center").RenderedAs(model => $"<a href='#' onclick='AbrirModalMaterial({model.Id_material})' data-placement='left'><span style='text-align:center'><i class='fa-solid fa-pen-to-square btn btn-info'></i></span></a>");
    })
.Empty("Sin registros encontrados")
.Named("gridMateriales")
.Id("gridMateriales")
.Pageable(pager =>
{
    pager.RowsPerPage = 10;
})
)

Views/Materiales/_ModalExistencia.cshtml
@model Sistema_Fallas_IMSS.ViewModels.VM_Existencias
@{
    Layout = null;
}
@Html.HiddenFor(model => model.Id_existencia)
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <label>Material:</label>
            @Html.DropDownListFor(model => model.Material, Model.Materiales, "Seleccione un tipo", new { @class = "form-control" })
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-md-6 col-lg-6">
            <label>Nombre de la persona:</label>
            @Html.TextBoxFor(model => model.Nombre_persona, "", new { @class = "form-control" })
        </div>
        <div class="col-sm-6 col-md-6 col-lg-6">
            <label>Area:</label>
            @Html.DropDownListFor(model => model.Area, Model.Areas, "Seleccione un area", new { @class = "form-control" })
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-md-6 col-lg-6">
            <label>Pc:</label>
            @Html.TextBoxFor(model => model.Pc, "", new { @class = "form-control" })
        </div>
        <div class="col-sm-6 col-md-6 col-lg-6">
            <label>Cuenta:</label>
            @Html.TextBoxFor(model => model.Cuenta, "", new { @class = "form-control" })
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-md-6 col-lg-6">
            <label>Direccion IP:</label>
            @Html.TextBoxFor(model => model.Direccion_ip, "", new { @class = "form-control" })
        </div>
        <div class="col-sm-6 col-md-6 col-lg-6">
            <label>Serial:</label>
            @Html.TextBoxFor(model => model.Serial, "", new { @class = "form-control" })
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-md-6 col-lg-6">
            <label>Nsm:</label>
            @Html.TextBoxFor(model => model.Nsm, "", new { @class = "form-control" })
        </div>
        <div class="col-sm-6 col-md-6 col-lg-6">
            <label>Nnn:</label>
            @Html.TextBoxFor(model => model.Nnn, "", new { @class = "form-control" })
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-md-6 col-lg-6">
            @Html.CheckBoxFor(model => model.Tipo) Existencia Global?
        </div>
    </div>
</div>

Views/Materiales/_ModalMaterial.cshtml
@model Sistema_Fallas_IMSS.ViewModels.VM_MaterialesCatalogo
@{
    Layout = null;
}
@Html.HiddenFor(model => model.Id_material)
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <label>Nombre:</label>
            @Html.TextBoxFor(model => model.Nombre, "", new { @class = "form-control" })
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-md-6 col-lg-6">
            <label>Marca:</label>
            @Html.TextBoxFor(model => model.Marca, "", new { @class = "form-control" })
        </div>
        <div class="col-sm-6 col-md-6 col-lg-6">
            <label>Modelo:</label>
            @Html.TextBoxFor(model => model.Modelo, "", new { @class = "form-control" })
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-md-6 col-lg-6">
            <label>Centro de costos:</label>
            @Html.TextBoxFor(model => model.Centro_costos, "", new { @class = "form-control" })
        </div>
        <div class="col-sm-6 col-md-6 col-lg-6">
            <label>Proyecto:</label>
            @Html.TextBoxFor(model => model.Proyecto, "", new { @class = "form-control" })
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-md-6 col-lg-6">
            <label>Tipo de Hardware:</label>
            @Html.DropDownListFor(model => model.Tipo_hardware, Model.Tipos, "Seleccione un tipo", new {@class = "form-control"})
        </div>
        <div class="col-sm-6 col-md-6 col-lg-6">
            <label>Estado:</label>
            @Html.DropDownListFor(model => model.Estado, Model.Estados, "Seleccione un estado", new { @class = "form-control" })
        </div>
    </div>
    <br />
    <div class="row">
        <label>Comentarios:</label>
        <div class="col-sm-12 col-md-12 col-lg-12">
            @Html.TextAreaFor(model => model.Comentarios, new { @class = "form-control", @rows = 5 })
        </div>
    </div>
</div>