Controllers/HospitalesController.cs
using Sistema_Fallas_IMSS.Models;
using Sistema_Fallas_IMSS.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace Sistema_Fallas_IMSS.Controllers
{
    public class HospitalesController : Controller
    {
        // GET: Hospitales
        [HttpGet]
        public ActionResult Index()
        {         

            return View();
        }

        public ActionResult HospitalesGrid()
        {
            using(var context = new IMSSEntities())
            {
                VM_Hospital data = new VM_Hospital
                {

                    Hospitales = (from hospital in context.hospitales_imss
                                  select new VM_Hospitales
                                  {
                                      Id = hospital.Id,
                                      Nombre = hospital.nombre,
                                      Director = hospital.director,
                                      Direccion = hospital.direccion,
                                      Municipio = hospital.municipio,
                                      Estado = hospital.estado,

                                  }).ToList(),
                }; 
                return PartialView("_HospitalesGrid", data);
            }
        }

        public ActionResult AreasGrid()
        {
            using(var context = new IMSSEntities())
            {
                VM_Area data = new VM_Area
                {
                    Areas = (from area in context.areas_imss
                             join hospital in context.hospitales_imss
                                on area.id_hospital equals hospital.Id
                             select new VM_Areas
                             {
                                 Id = area.Id_area,
                                 Nombre_area = area.nombre_area,
                                 Id_hospital = area.id_hospital,
                                 Hospital = hospital.nombre,
                             }).ToList(),
                };
                return PartialView("_AreasGrid", data);
            }
        }

        [HttpPost]
        public ActionResult AbrirModalHospital(int _id_hospital)
        {
            using(var context = new IMSSEntities())
            {
                VM_Hospitales data = new VM_Hospitales();
                if (_id_hospital > 0)
                {
                    var hospital = context.hospitales_imss.Find(_id_hospital);

                    data = new VM_Hospitales{
                        Id = hospital.Id,
                        Nombre = hospital.nombre,
                        Director = hospital.director,
                        Direccion = hospital.direccion,
                        Municipio = hospital.municipio,
                        Estado = hospital.estado,
                    };
                }

                return PartialView("_ModalHospital",data);
            }
           
        }

        [HttpPost]
        public ActionResult AbrirModalArea(int _id_area)
        {
            using(var context = new IMSSEntities())
            {
                VM_Areas data = new VM_Areas();
                if (_id_area > 0)
                {
                    var area = context.areas_imss.Find(_id_area);
                    data.Id = area.Id_area;
                    data.Nombre_area = area.nombre_area;
                    data.Id_hospital = area.id_hospital;
                    data.Hospital = area.id_hospital.ToString();
                    
                }
                data.Hospitales = (from hospitales in context.hospitales_imss
                                   select new SelectListItem
                                   {
                                       Value = hospitales.Id.ToString(),
                                       Text = hospitales.nombre,
                                   }).ToList();
                return PartialView("_ModalAreas", data);
            }
        }

        [HttpPost]
        public int RegistrarEditarHospital(VM_Hospitales _hospital)
        {
            using (var context = new IMSSEntities())
            {
                try
                {
                    if (_hospital.Id > 0)
                    {
                        var hospital = context.hospitales_imss.Find(_hospital.Id);
                        hospital.nombre = _hospital.Nombre;
                        hospital.director = _hospital.Director;
                        hospital.direccion = _hospital.Direccion;
                        hospital.municipio = _hospital.Municipio;
                        hospital.estado = _hospital.Estado;
                    }
                    else
                    {
                        hospitales_imss hospital = new hospitales_imss
                        {
                            nombre = _hospital.Nombre,
                            director = _hospital.Director,
                            direccion = _hospital.Direccion,
                            municipio = _hospital.Municipio,
                            estado = _hospital.Estado,
                        };
                        context.hospitales_imss.Add(hospital);

                    }
                    context.SaveChanges();
                    return 1;
                }
                catch (Exception)
                {
                    return 0;
                    throw;
                }
                
            }
           
        }

        [HttpPost]
        public int RegistrarEditarArea(VM_Areas _area)
        {
            using(var context = new IMSSEntities())
            {
                try
                {
                    if (_area.Id > 0)
                    {
                        var area = context.areas_imss.Find(_area.Id);
                        area.nombre_area = _area.Nombre_area;
                        area.id_hospital = _area.Id_hospital;

                    }
                    else
                    {
                        areas_imss area = new areas_imss
                        {
                            nombre_area = _area.Nombre_area,
                            id_hospital = _area.Id_hospital,
                        };
                        context.areas_imss.Add(area);
                    }
                    context.SaveChanges();
                    return 1;
                }
                catch (Exception)
                {
                    return 0;
                    throw;
                }
            }
        }
    }
}

Views/Hospitales/Index.cshtml
@using NonFactors.Mvc.Grid
@model Sistema_Fallas_IMSS.ViewModels.VM_Hospital
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="hospital-tab" data-bs-toggle="tab" data-bs-target="#hospitales" type="button" role="tab" aria-controls="hospitales" aria-selected="true">Hospitales</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="area-tab" data-bs-toggle="tab" data-bs-target="#areas" type="button" role="tab" aria-controls="areas" aria-selected="false">Areas</button>
    </li>
</ul>
<div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="hospitales" role="tabpanel" aria-labelledby="hospital-tab">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <section class="content-header">
                    <div class="row bottom30">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <h3 style="margin-top: 10px; text-align:center;">Hospitales</h3>
                        </div>
                    </div>
                </section>
                <section class="content">
                    <br />
                    <div>
                        <button class="btn btn-primary" onclick="AbrirModalHospital(0)">Registrar Hospital</button>
                    </div>
                    <br />
                    @Html.AjaxGrid(Url.Action("HospitalesGrid", "Hospitales",
                    new
                         {
                            _usuario = User.Identity.Name,

                    }), new { id = "gridHospitales", name = "gridHospitales" })
                </section>
            </div>
        </div>
    </div>

    <div class="tab-pane fade" id="areas" role="tabpanel" aria-labelledby="area-tab">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <section class="content-header">
                    <div class="row bottom30">
                        <br />
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <h3 style="margin-top: 10px; text-align:center;">Areas</h3>
                        </div>
                    </div>
                </section>
                <section class="content">
                    <br />
                    <div>
                        <button class="btn btn-primary" onclick="AbrirModalArea(0)">Registrar Area</button>
                    </div>
                    <br />
                    @Html.AjaxGrid(Url.Action("AreasGrid", "Hospitales",
                    new
                         {
                            _usuario = User.Identity.Name,

                    }), new { id = "gridAreas", name = "gridAreas" })
                </section>
            </div>
        </div>
    </div>
    <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">

    </div>
</div>

<!--Modal para Editar/Crear Hospitales-->
<div id="mdl_Hopsitales" class="modal fade" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Hospital</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <br />
            <div class="modal-body">

                <!-- PartialView _ModalHospital.cshtml -->

            </div>
            <!-- Modal footer -->
            <div class=" modal-footer">
                <button type="button" class="btn btn-success" onclick="RegistrarEditarHospital()">Guardar</button>
            </div>
        </div>
    </div>
</div>
<!--Modal para Editar/Crear Areas-->
<div id="mdl_Areas" class="modal fade" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Area</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <br />
            <div class="modal-body">

                <!-- PartialView _ModalArea.cshtml -->

            </div>
            <!-- Modal footer -->
            <div class=" modal-footer">
                <button type="button" class="btn btn-success" onclick="RegistrarEditarArea()">Guardar</button>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/MvcGrid/mvc-grid.js"></script>
<script type="text/javascript">

    window.onload = (event) => {

        [].forEach.call(document.getElementsByClassName('mvc-grid'), function (element) {
            new MvcGrid(element);
        });
    }

    function AbrirModalHospital(id_hospital) {
        $.ajax({
            type: "POST",
            url: '@Href("~/Hospitales/AbrirModalHospital")',
            data: JSON.stringify({ _id_hospital: id_hospital }),
            contentType: "application/json; charset=utf-8",
            dataType: "html",
            success: function (response) {

                $("#mdl_Hopsitales").find(".modal-body").html(response);
                $("#mdl_Hopsitales").modal('show');

            },
            failure: function (response) {
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            },
        });
    }
    function AbrirModalArea(id_area) {
        $.ajax({
            type: "POST",
            url: '@Href("~/Hospitales/AbrirModalArea")',
            data: JSON.stringify({ _id_area: id_area }),
            contentType: "application/json; charset=utf-8",
            dataType: "html",
            success: function (response) {

                $("#mdl_Areas").find(".modal-body").html(response);
                $("#mdl_Areas").modal('show');

            },
            failure: function (response) {
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            },
        });
    }

    function RegistrarEditarHospital() {

        var formData = new FormData();
        formData.append("Id", $("#Id").val());
        formData.append("Nombre", $("#Nombre").val());
        formData.append("Director", $("#Director").val());
        formData.append("Direccion", $("#Direccion").val());
        formData.append("Municipio", $("#Municipio").val());
        formData.append("Estado", $("#Estado").val());

         $.ajax({
            type: "POST",
            url: '@Href("~/Hospitales/RegistrarEditarHospital")',
            data: formData,
            contentType: false,
            dataType: "json",
            cache: false,
            processData: false,
            success: function (response) {

                if (response == 1) {
                    $("#mdl_Hopsitales").modal('hide');
                    var grid = new MvcGrid(document.querySelector(".mvc-grid"))
                    grid.reload();
                }

            },
            failure: function (response) {
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            },
        });
    }

    function RegistrarEditarArea() {
        var formData = new FormData();
        formData.append("Id", $("#Id").val());
        formData.append("Nombre_area", $("#Nombre_area").val());
        formData.append("Id_hospital", $("#Hospital").val());

         $.ajax({
            type: "POST",
            url: '@Href("~/Hospitales/RegistrarEditarArea")',
            data: formData,
            contentType: false,
            dataType: "json",
            cache: false,
            processData: false,
            success: function (response) {

                if (response == 1) {
                    $("#mdl_Areas").modal('hide');

                    var grid = new MvcGrid(document.querySelector("#gridAreas"))
                    grid.reload();
                    var grid2 = new MvcGrid(document.querySelector("#gridHospitales"))
                    grid2.reload();
                }

            },
            failure: function (response) {
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            },
        });
    }

</script>

Views/Hospitales/_AreasGrid.cshtml
@using NonFactors.Mvc.Grid
@model Sistema_Fallas_IMSS.ViewModels.VM_Area
@(Html.Grid(Model.Areas)
    .Build(columns =>
    {
        columns.Add(model => model.Id).Hidden();
        columns.Add(model => model.Nombre_area).Titled("Area");
        columns.Add(model => model.Hospital).Titled("Hospital");
        columns.Add(model => model.Id).Titled("Editar").Encoded(false).Css("text-center").RenderedAs(model => $"<a href='#' onclick='AbrirModalArea({model.Id})' data-placement='left'><span style='text-align:center'><i class='fa-solid fa-pen-to-square btn btn-info'></i></span></a>");
    })
.Empty("Sin registros encontrados")
.Named("gridAreas")
.Id("gridAreas")
.Pageable(pager =>
{
    pager.RowsPerPage = 10;
})
)

Views/Hospitales/_HospitalesGrid.cshtml
@using NonFactors.Mvc.Grid
@model Sistema_Fallas_IMSS.ViewModels.VM_Hospital
@(Html.Grid(Model.Hospitales)
    .Build(columns =>
    {
        columns.Add(model => model.Id).Hidden();
        columns.Add(model => model.Nombre).Titled("Nombre");
        columns.Add(model => model.Director).Titled("Director");
        columns.Add(model => model.Estado).Titled("Estado");
        columns.Add(model => model.Municipio).Titled("Municipio");
        columns.Add(model => model.Direccion).Titled("Direccion");
        columns.Add(model => model.Id).Titled("Editar").Encoded(false).Css("text-center").RenderedAs(model => $"<a href='#' onclick='AbrirModalHospital({model.Id})' data-placement='left'><span style='text-align:center'><i class='fa-solid fa-pen-to-square btn btn-info'></i></span></a>");
    })
.Empty("Sin registros encontrados")
.Named("gridHospitales")
.Id("gridHospitales")
.Pageable(pager =>
{
    pager.RowsPerPage = 10;
})
)

Views/Hospitales/_ModalAreas.cshtml
@model Sistema_Fallas_IMSS.ViewModels.VM_Areas
@{
    Layout = null;
}
@Html.HiddenFor(model => model.Id)
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <label>Nombre:</label>
            @Html.TextBoxFor(model => model.Nombre_area, "", new { @class = "form-control" })
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <label>Hospital:</label>
            @Html.DropDownListFor(model => model.Hospital, Model.Hospitales, "Seleccione Hospital" ,new {@class = "form-control"})
        </div>
    </div>      
</div>

Views/Hospitales/_ModalHospital.cshtml
@model Sistema_Fallas_IMSS.ViewModels.VM_Hospitales
@{
    Layout = null;
}
@Html.HiddenFor(model => model.Id)
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <label>Nombre:</label>
            @Html.TextBoxFor(model => model.Nombre, "", new {@class = "form-control"})
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4 col-md-4 col-lg-4">
            <label>Director:</label>
            @Html.TextBoxFor(model => model.Director, "", new { @class = "form-control" })
        </div>
        <div class="col-sm-8 col-md-8 col-lg-8">
            <label>Direccion:</label>
            @Html.TextBoxFor(model => model.Direccion, "", new { @class = "form-control" })
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-md-6 col-lg-6">
            <label>Municipio:</label>
            @Html.TextBoxFor(model => model.Municipio, "", new { @class = "form-control" })
        </div>
        <div class="col-sm-6 col-md-6 col-lg-6">
            <label>Estado:</label>
            @Html.TextBoxFor(model => model.Estado, "", new { @class = "form-control" })
        </div>
    </div>
</div>